version: '3'

services:
  jupyterhub:
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
    environment:
      DOCKER_JUPYTER_CONTAINER: jupyterlab_img
      DOCKER_NETWORK_NAME: ${COMPOSE_PROJECT_NAME}_jupyter
      HUB_IP: jupyterhub_hub
    networks:
      default:
      jupyter:
        aliases:
          - jupyterhub_hub
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:sage.prism.uvsq.fr"
    restart: on-failure

  jupyterlab:
    build: jupyterlab
    image: jupyterlab_img
    container_name: jupyterlab-throaway
    network_mode: none
    command: echo

  reverse-proxy:
    image: traefik
    container_name: reverse-proxy
    ports:
      - "8000:80"
      - "8001:8080"
    volumes:
      - ./reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

  oauth2_server:
    image: defeo/cas2oauth2bridge
    container_name: c2o2b
    volumes:
      - ./oauth2/config.js:/home/node/config.js
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:sage.prism.uvsq.fr;PathPrefixStrip:/c2o2b/"
    restart: on-failure

volumes:
  jupyterhub_data:

networks:
  jupyter:
    internal: true
